### ISSUE TITLE
Doesn't work on the latest version of preact-cli

### ISSUE THREAD

**Issue by pmcalmeida** [robinvdvleuten/preact-cli-plugin-styled-components#1]
Error: Error at /Users/palmeida/Projects/akropolis/preact.config.js:
TypeError: Cannot read property 'getLoadersByName' of undefined

**Comment by ghost** [comment]
same issue here, did you find a solution?

**Comment by pmcalmeida** [comment]
@coder82 nope :( give up and used post-css
